### ISSUE TITLE
Will it be out of the box as  Helix? 

### ISSUE THREAD

**Issue by SadSock** [rsvim/rsvim#132]
Will it integrate plugins like LSP, treesitter, which-key, telescope, multicursor etc out of the box like Helix?

**Comment by linrongbin16** [comment]
Currently I am the only one working on it. I guess it won't contain all functions like other editors in first few versions.

I will try do make it happen, welcome to contribute.

**Comment by SadSock** [comment]
it will integrate lsp and treesitter？

**Comment by linrongbin16** [comment]
hi, :) 

I think lsp/treesitter are worth to integrate because they are so close to text edting, coding editing and programming tools.

But the actual development progress is so slow, I cannot really give you some timeline about them. For now this is more like an experiment, hope I can throw more time on it.
